export const search = [
    "phone",
    "running shoes",
    "backpack",
    "wireless headphones",
    "kitchen mixer",
    "yoga mat",
    "water bottle",
    "smartwatch",
    "bookshelf",
    "sunglasses",
    "laptop",
    "bluetooth speaker",
    "fitness tracker",
    "women",
    "men",
    "skincare",
    "electric toothbrush",
    "gaming console",
    "LED TV",
    "coffee maker",
    "blender",
    "robot vacuum",
    "air fryer",
    "sneakers",
    "jeans",
    "t-shirts",
    "handbags",
    "watches",
    "jackets",
    "dress",
    "bed sheets",
    "towels",
    "scented candles",
    "skincare products",
    "hair dryer",
    "perfume",
    "makeup kit",
    "novels",
    "board games",
    "bike helmet",
    "tent",
    "camping gear",
    "fishing rod",
    "plant pots",
    "garden tools",
    "pet food",
    "cat toys",
    "dog leash",
    "baby stroller",
    "kids' toys",
    "puzzles",
    "art supplies",
    "office chair"
  ]
  